"""Generate a merge-ready evidence pack without filesystem writes or dependencies."""

from __future__ import annotations

from io import BytesIO
import json
from typing import Any
from zipfile import ZIP_DEFLATED, ZipFile, ZipInfo


def build_evidence_pack(assessment: dict[str, Any]) -> bytes:
    files = evidence_files(assessment)
    buffer = BytesIO()
    with ZipFile(buffer, "w", compression=ZIP_DEFLATED, compresslevel=9) as archive:
        for path, content in files.items():
            info = ZipInfo(path, date_time=(2026, 8, 8, 0, 0, 0))
            info.compress_type = ZIP_DEFLATED
            info.external_attr = 0o644 << 16
            archive.writestr(info, content)
    return buffer.getvalue()


def evidence_files(assessment: dict[str, Any]) -> dict[str, str]:
    request = assessment["request"]
    source = assessment["source"]
    old = request["column"]
    new = request.get("replacement") or old
    if request["action"] == "type_change":
        new = f"{old}_v2"
    dataset = request["dataset"]
    field_type = source.get("field", {}).get("type", "STRING")
    model_name = dataset.split(".")[-1]

    if request["action"] in {"drop", "deprecate"}:
        compatibility_sql = f"""-- Generated by Ripplecheck {assessment['change_capsule']['capsule_id']}
-- Keep the existing field through a measured compatibility window.
CREATE OR REPLACE VIEW {dataset}_compat AS
SELECT *
FROM {dataset};

-- Retirement is allowed only after gate G1 opens and DataHub reports zero consumers.
"""
    else:
        compatibility_sql = f"""-- Generated by Ripplecheck {assessment['change_capsule']['capsule_id']}
-- Phase 1: add and backfill the replacement without removing the old contract.
ALTER TABLE {dataset}
  ADD COLUMN IF NOT EXISTS {new} {field_type};

UPDATE {dataset}
SET {new} = {old}
WHERE {new} IS NULL;

-- Phase 2: downstream consumers read through both names during migration.
CREATE OR REPLACE VIEW {dataset}_compat AS
SELECT
  * EXCLUDE ({old}, {new}),
  {old},
  {new}
FROM {dataset};
"""
    if request["action"] in {"drop", "deprecate"}:
        schema_yml = f"""version: 2

models:
  - name: {model_name}
    config:
      contract:
        enforced: true
    columns:
      - name: {old}
        data_type: {field_type.lower()}
        description: Deprecated compatibility field; remove only after Ripplecheck gate G1 opens.
        meta:
          deprecated: true
          release_gate: G1
"""
    else:
        schema_yml = f"""version: 2

models:
  - name: {model_name}
    config:
      contract:
        enforced: true
    columns:
      - name: {old}
        data_type: {field_type.lower()}
        description: Compatibility field; remove only after Ripplecheck gate G1 opens.
        meta:
          deprecated: true
          replacement: {new}
      - name: {new}
        data_type: {field_type.lower()}
        description: Replacement field generated from the approved schema migration.
"""
    if request["action"] in {"drop", "deprecate"}:
        parity_test = f"""-- Fails while a consumer still depends on the deprecated field.
-- Replace this fixture assertion with the live DataHub lineage query in CI.
SELECT '{old}' AS blocked_field
WHERE 1 = {1 if assessment['blast_radius'] else 0}
"""
    else:
        parity_test = f"""-- Returns rows only when the compatibility contract is violated.
SELECT *
FROM {dataset}
WHERE {old} IS DISTINCT FROM {new}
   OR {new} IS NULL
"""
    decision = decision_markdown(assessment)
    routing = json.dumps(
        {
            "capsule_id": assessment["change_capsule"]["capsule_id"],
            "release_gate": assessment["release_gate"],
            "routes": [
                {
                    "asset": asset["name"],
                    "owners": asset.get("owners") or ["UNOWNED"],
                    "lineage_path": asset.get("lineage_path", []),
                    "required_action": "migrate consumer and attest parity",
                }
                for asset in assessment["blast_radius"]
            ],
        },
        indent=2,
        sort_keys=True,
    ) + "\n"
    capsule = json.dumps(
        {
            **assessment["change_capsule"],
            "request": assessment["request"],
            "release_gate": assessment["release_gate"],
            "policy_proof": assessment["policy_proof"],
            "artifact_manifest": assessment["artifact_manifest"],
        },
        indent=2,
        sort_keys=True,
    ) + "\n"
    model_path = f"models/{model_name}/schema.yml"
    test_path = f"tests/assert_{old}_compatibility.sql"
    return {
        "migration/compatibility_view.sql": compatibility_sql,
        model_path: schema_yml,
        test_path: parity_test,
        "review/ripplecheck-decision.md": decision,
        "review/owner-routing.json": routing,
        "manifest/change-capsule.json": capsule,
    }


def decision_markdown(assessment: dict[str, Any]) -> str:
    policies = "\n".join(
        f"- `{item['id']}` **{item['status']}**: {item['evidence']}"
        for item in assessment["policy_proof"]
    )
    paths = "\n".join(
        f"- `{' -> '.join(asset.get('lineage_path', []))}`"
        for asset in assessment["blast_radius"]
    ) or "- No downstream lineage paths found."
    return f"""# Ripplecheck release decision

**Capsule:** `{assessment['change_capsule']['capsule_id']}`  
**Decision:** `{assessment['decision']}`  
**Release gate:** `{assessment['release_gate']['status']}`  
**Proposed change:** `{assessment['request']['raw']}`

## Why

{assessment['headline']}

## Policy proof

{policies}

## Lineage evidence

{paths}

## Release condition

{assessment['release_gate']['release_condition']}

Generated deterministically from the DataHub MCP evidence path.
"""
