-- Generated by Ripplecheck RC-DAE79F33A169
-- Phase 1: add and backfill the replacement without removing the old contract.
ALTER TABLE warehouse.finance.monthly_revenue
  ADD COLUMN IF NOT EXISTS recognized_revenue NUMBER(18,2);

UPDATE warehouse.finance.monthly_revenue
SET recognized_revenue = net_revenue
WHERE recognized_revenue IS NULL;

-- Phase 2: downstream consumers read through both names during migration.
CREATE OR REPLACE VIEW warehouse.finance.monthly_revenue_compat AS
SELECT
  * EXCLUDE (net_revenue, recognized_revenue),
  net_revenue,
  recognized_revenue
FROM warehouse.finance.monthly_revenue;
