-- Generated by Ripplecheck RC-4AC01328A4AA
-- Phase 1: add and backfill the replacement without removing the old contract.
ALTER TABLE warehouse.analytics.customer_360
  ADD COLUMN IF NOT EXISTS loyalty_tier STRING;

UPDATE warehouse.analytics.customer_360
SET loyalty_tier = customer_tier
WHERE loyalty_tier IS NULL;

-- Phase 2: downstream consumers read through both names during migration.
CREATE OR REPLACE VIEW warehouse.analytics.customer_360_compat AS
SELECT
  * EXCLUDE (customer_tier, loyalty_tier),
  customer_tier,
  loyalty_tier
FROM warehouse.analytics.customer_360;
