-- Generated by Ripplecheck RC-E10A9BC94150
-- Keep the existing field through a measured compatibility window.
CREATE OR REPLACE VIEW warehouse.sandbox.experiment_flags_compat AS
SELECT *
FROM warehouse.sandbox.experiment_flags;

-- Retirement is allowed only after gate G1 opens and DataHub reports zero consumers.
